branches:
  only:
    - 'master'

language: ruby
rvm:
  - 1.9.2
  - 1.9.3

env:
  - DB=postgres BUILD_TYPE=other

bundler_args: "--without development production heroku"
before_script: "./script/ci/before.sh"
script: "bundle exec rake travis"

notifications:
  irc:
    channels:
      - 'irc.freenode.org:6667#codeforamerica'
