branches:
  only:
    - 'master'

language: ruby
rvm:
  - 1.9.2
  - 1.9.3

env:
  - DB=postgres BUILD_TYPE=other
  - DB=postgres BUILD_TYPE=cucumber

bundler_args: "--without development production heroku"
before_script:
  - "./script/ci/before.sh"
  - bundle exec rake sunspot:solr:start
script: "bundle exec rake travis"

notifications:
  irc:
    channels:
      - 'irc.freenode.org:6667#codeforamerica'
