before_script:
  - bundle exec rake db:create db:migrate test
  - bundle exec rake sunspot:solr:start
bundler_args: "--without assets:development:production"
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
script:
  - bundle exec rake cucumber
  - bundle exec rake spec
